tests
test0070RefactorUsingSetUp
"
You can simplify your code using `setUp`.

Now, you can use setUp method to create a `WasRun` instance.

Please pass the test below on Playground.
( Same as the previous test )
```
(TestCazeTest name: 'testRunning') run
(TestCazeTest name: 'testSetUp') run
```

If the test is success, nothing is happened.
If the test is failed, you will see some stacktrace.

https://github.com/yujihamaguchi/little-smalltalker-filetree/tree/330c79cb1aa81359681508f1182fb18c92312740/Q110-xUnit_work.package
"