tests
test0080Logging
"
You should stop using flags to check if it has been executed and instead use a log.
WasRun log -> 'setUp testMethod ' 

Please pass the test below on Playground.
```
(TestCazeTest name: 'testTemplateMethod') run
```

If the test is success, nothing is happened.
If the test is failed, you will see some stacktrace.

https://github.com/yujihamaguchi/little-smalltalker-filetree/tree/72967549255473654f785ac55a4c1578195b3a31/Q110-xUnit_work.package
"