tests
test0050UseOurTestCazeClass
"
You should use your `TestCaze` class to execute test case.

Please pass the test below on Playground.

```
(TestCazeTest name: 'testRunning') run
```

You will not see anymore on a Transcript.
If the test is success, nothing is happened.
If the test is failed, you will see some stacktrace.

https://github.com/yujihamaguchi/little-smalltalker-filetree/tree/eb4144c89b76ec197c72550f860bf55bf498898d/Q110-xUnit_work.package
"