tests
test0090TearDown
"
It's easy to add `tearDown`.

Please pass the test below on Playground.
( Same as the previous test )
```
(TestCazeTest name: 'testTemplateMethod') run
```

If the test is success, nothing is happened.
If the test is failed, you will see some stacktrace.

https://github.com/yujihamaguchi/little-smalltalker-filetree/tree/c9d0c40f0be29c2f88817ae5db616e0084ea1730/Q110-xUnit_work.package
"