tests
test0060SetUp
"
We want to add `setup` process before execution of test.

Please pass the test below on Playground.

```
(TestCazeTest name: 'testRunning') run.
(TestCazeTest name: 'testSetUp') run
```

If the test is success, nothing is happened.
If the test is failed, you will see some stacktrace.

https://github.com/yujihamaguchi/little-smalltalker-filetree/tree/f57a816cb13483c682df5159e84953897c0280c3/Q110-xUnit_work.package
"