tests
test0110CountTest
"
You should return object `TestRezult` which has a `runCount` variable.

Please pass the test below on Playground.
( Same as the previous test )
```
(TestCazeTest name: 'testTemplateMethod') run.
(TestCazeTest name: 'testRezult') run
```

If the test is success, nothing is happened.
If the test is failed, you will see some stacktrace.

https://github.com/yujihamaguchi/little-smalltalker-filetree/tree/98a03a867066fbc6f7a1bba6552639d71e1d5aaf/Q110-xUnit_work.package
"